POST http://localhost:3000/api/contact/ HTTP/1.1
content-type: application/json

{
    "adress": {
        "az": "[AZ]349 Main St, Deseronto, ON K0K 1X0, Canada",
        "en": "[EN]349 Main St, Deseronto, ON K0K 1X0, Canada",
        "ru": "[RU]349 Main St, Deseronto, ON K0K 1X0, Canada"
    },
    "phones": ["+00 123 456 789 00", "+ 00 254 632 548 00"],
    "emails": ["support@alphachem.com", "help.alphachem@gmail.com"],
    "location": {
      "lat": "40.4736823",
      "long":"49.9491262"
    }
}

###

PUT http://localhost:5000/api/contact/ HTTP/1.1
content-type: application/json

{
    "adress": {
        "az": "[AZ]349 Main St, Deseronto, ON K0K 1X0, Canada",
        "en": "[EN]349 Main St, Deseronto, ON K0K 1X0, Canada",
        "ru": "[RU]349 Main St, Deseronto, ON K0K 1X0, Canada"
    },
    "phones": ["+00 123 456 789ssss1q123 00", "+ 00 254 632 548 00"],
    "emails": ["support@alphachem.com", "help.alphachem@gmail.com"],
    "location": {
      "lat": "40.4736823",
      "long":"49.9491262"
    }
}

###

POST http://localhost:3000/api/about/ HTTP/1.1
content-type: application/json

{
    "title": {
      "az": "[AZ] About title 3",
      "en": "[EN] About title 3",
      "ru": "[RU] About title 3"
    },
    "description": {
      "az": "[AZ] About description asda da dsa dasdkjhkjhkj sasdsa dakj kjadsj asd bbfadkaakjbfs sadasdkj",
      "en": "[EN] About description asda da dsa dasdkjhkjhkj sasdsa dakj kjadsj asd bbfadkaakjbfs sadasdkj",
      "ru": "[RU] About description asda da dsa dasdkjhkjhkj sasdsa dakj kjadsj asd bbfadkaakjbfs sadasdkj"
    }
}

###

PUT http://localhost:3000/api/about/5ea079b28808f54914393501 HTTP/1.1
content-type: application/json

{
    "title": {
      "az": "[AZ] About title 3",
      "en": "[EN] About title 3",
      "ru": "[RU] About title 3"
    },
    "description": {
      "az": "[AZ] About description asda da dsa dasdkjhkjhkj sasdsa dakj kjadsj asd bbfadkaakjbfs sadasdkj",
      "en": "[EN] About description asda da dsa dasdkjhkjhkj sasdsa dakj kjadsj asd bbfadkaakjbfs sadasdkj",
      "ru": "[RU] About description asda da dsa dasdkjhkjhkj sasdsa dakj kjadsj asd bbfadkaakjbfs sadasdkj"
    }
}

###

DELETE  http://localhost:3000/api/about/5ea079b28808f54914393501 HTTP/1.1

###

POST http://localhost:3000/api/products/ HTTP/1.1
content-type: application/json

{
    "title": {
      "az": "[AZ]vaseline",
      "en": "[EN]vaseline",
      "ru": "[RU]vaseline"
    },
    "imageSrc": "/products/vaseline.jpg"
}

###

PUT http://localhost:3000/api/products/5ea0b03af774454d211ac061 HTTP/1.1
content-type: application/json

{
    "title": {
      "az": "[AZ]product - 7",
      "en": "[EN]product - 7",
      "ru": "[RU]product - 7"
    },
    "imageSrc": "/products/7.png"
}

###

DELETE  http://localhost:3000/api/products/5ea08439bf6faf65247bd4b5 HTTP/1.1


###


POST http://localhost:3000/api/slider/ HTTP/1.1
content-type: application/json

{
    "title": {
      "az": "[AZ]Slider title 1",
      "en": "[EN]Slider title 1",
      "ru": "[RU]Slider title 1"
    },
    "description": {
      "az": "[AZ]Slider description 1",
      "en": "[EN]Slider description 1",
      "ru": "[RU]Slider description 1"
    },
    "imageSrc": "/slider/slider-1.jpg"
}

###

PUT http://localhost:3000/api/slider/5ea087b5d8c772289cc28db4 HTTP/1.1
content-type: application/json

{
    "title": {
      "az": "[AZ]Slider title 2",
      "en": "[EN]Slider title 2",
      "ru": "[RU]Slider title 2"
    },
    "description": {
      "az": "[AZ]Slider description 2",
      "en": "[EN]Slider description 2",
      "ru": "[RU]Slider description 2"
    },
    "imageSrc": "/slider/slider-2.jpg"
}

###

DELETE  http://localhost:3000/api/slider/5ea087c3d8c772289cc28db5 HTTP/1.1