export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_COMPLETE = 'GET_PRODUCTS_COMPLETE';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const ADD_PRODUCTS_COMPLETE = 'ADD_PRODUCTS_COMPLETE';
export const ADD_PRODUCTS_ERROR = 'ADD_PRODUCTS_ERROR';

export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const UPDATE_PRODUCTS_COMPLETE = 'UPDATE_PRODUCTS_COMPLETE';
export const UPDATE_PRODUCTS_ERROR = 'UPDATE_PRODUCTS_ERROR';

export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const DELETE_PRODUCTS_COMPLETE = 'DELETE_PRODUCTS_COMPLETE';
export const DELETE_PRODUCTS_ERROR = 'DELETE_PRODUCTS_ERROR';

export const GET_SLIDER = 'GET_SLIDER';
export const GET_SLIDER_COMPLETE = 'GET_SLIDER_COMPLETE';
export const GET_SLIDER_ERROR = 'GET_SLIDER_ERROR';

export const ADD_SLIDER = 'ADD_SLIDER';
export const ADD_SLIDER_COMPLETE = 'ADD_SLIDER_COMPLETE';
export const ADD_SLIDER_ERROR = 'ADD_SLIDER_ERROR';

export const UPDATE_SLIDER = 'UPDATE_SLIDER';
export const UPDATE_SLIDER_COMPLETE = 'UPDATE_SLIDER_COMPLETE';
export const UPDATE_SLIDER_ERROR = 'UPDATE_SLIDER_ERROR';

export const DELETE_SLIDER = 'DELETE_SLIDER';
export const DELETE_SLIDER_COMPLETE = 'DELETE_SLIDER_COMPLETE';
export const DELETE_SLIDER_ERROR = 'DELETE_SLIDER_ERROR';

export const GET_ABOUT = 'GET_ABOUT';
export const GET_ABOUT_COMPLETE = 'GET_ABOUT_COMPLETE';
export const GET_ABOUT_ERROR = 'GET_ABOUT_ERROR';

export const ADD_ABOUT = 'ADD_ABOUT';
export const ADD_ABOUT_COMPLETE = 'ADD_ABOUT_COMPLETE';
export const ADD_ABOUT_ERROR = 'ADD_ABOUT_ERROR';

export const UPDATE_ABOUT = 'UPDATE_ABOUT';
export const UPDATE_ABOUT_COMPLETE = 'UPDATE_ABOUT_COMPLETE';
export const UPDATE_ABOUT_ERROR = 'UPDATE_ABOUT_ERROR';

export const DELETE_ABOUT = 'DELETE_ABOUT';
export const DELETE_ABOUT_COMPLETE = 'DELETE_ABOUT_COMPLETE';
export const DELETE_ABOUT_ERROR = 'DELETE_ABOUT_ERROR';

export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACTS_COMPLETE = 'GET_CONTACTS_COMPLETE';
export const GET_CONTACTS_ERROR = 'GET_CONTACTS_ERROR';

export const ADD_CONTACTS = 'ADD_CONTACTS';
export const ADD_CONTACTS_COMPLETE = 'ADD_CONTACTS_COMPLETE';
export const ADD_CONTACTS_ERROR = 'ADD_CONTACTS_ERROR';

export const UPDATE_CONTACTS = 'UPDATE_CONTACTS';
export const UPDATE_CONTACTS_COMPLETE = 'UPDATE_CONTACTS_COMPLETE';
export const UPDATE_CONTACTS_ERROR = 'UPDATE_CONTACTS_ERROR';

export const DELETE_CONTACTS = 'DELETE_ABOUT';
export const DELETE_CONTACTS_COMPLETE = 'DELETE_CONTACTS_COMPLETE';
export const DELETE_CONTACTS_ERROR = 'DELETE_CONTACTS_ERROR';
